version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
  disable:
    - errcheck
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives

issues:
  max-issues-per-linter: 20
  max-same-issues: 5

run:
  timeout: 5m
