package models

import "time"

// User represents a user account.
type User struct {
	ID           int64     `json:"id" example:"1"`
	Username     string    `json:"username" example:"admin"`
	PasswordHash string    `json:"-"`
	Role         string    `json:"role" example:"admin"`
	TOTPSecret   *string   `json:"-"`
	TOTPEnabled  bool      `json:"totp_enabled" example:"false"`
	TokenVersion int64     `json:"-"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// Invitation represents a user invitation code.
type Invitation struct {
	ID        int64      `json:"id"`
	Code      string     `json:"code"`
	Role      string     `json:"role"`
	CreatedBy int64      `json:"created_by"`
	UsedBy    *int64     `json:"used_by"`
	UsedAt    *time.Time `json:"used_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	CreatedAt time.Time  `json:"created_at"`
}

// Role constants.
const (
	RoleAdmin  = "admin"
	RoleEditor = "editor"
	RoleViewer = "viewer"
)

// ValidRoles contains all valid role values.
var ValidRoles = []string{RoleAdmin, RoleEditor, RoleViewer}

// IsValidRole checks if a role string is valid.
func IsValidRole(role string) bool {
	for _, r := range ValidRoles {
		if r == role {
			return true
		}
	}
	return false
}

// SetupRequest is the payload for POST /api/auth/setup.
type SetupRequest struct {
	Username string `json:"username" example:"admin"`
	Password string `json:"password" example:"strongpassword"`
}

// SetupResponse is the response from POST /api/auth/setup.
type SetupResponse struct {
	Message string `json:"message"`
	User    User   `json:"user"`
}

// LoginRequest is the payload for POST /api/auth/login.
type LoginRequest struct {
	Username string `json:"username" example:"admin"`
	Password string `json:"password" example:"strongpassword"`
	TOTPCode string `json:"totp_code,omitempty" example:"123456"`
}

// LoginResponse is the response from POST /api/auth/login.
type LoginResponse struct {
	Message string `json:"message" example:"login successful"`
	User    User   `json:"user"`
}

// TOTPGenerateResponse is the response from POST /api/auth/totp/generate.
type TOTPGenerateResponse struct {
	Secret string `json:"secret"`
	URL    string `json:"url"`
	QR     string `json:"qr"`
}

// TOTPEnableRequest is the payload for POST /api/auth/totp/enable.
type TOTPEnableRequest struct {
	Code string `json:"code"`
}

// AuthStatusResponse is the response from GET /api/auth/status.
type AuthStatusResponse struct {
	SetupCompleted bool `json:"setup_completed"`
}

// RegisterRequest is the payload for POST /api/auth/register (via invite).
type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Code     string `json:"code"`
}

// UpdateAccountRequest is the payload for PUT /api/auth/account.
type UpdateAccountRequest struct {
	CurrentPassword string  `json:"current_password"`
	Username        *string `json:"username,omitempty"`
	NewPassword     *string `json:"new_password,omitempty"`
}

// UpdateAccountResponse is the response from PUT /api/auth/account.
type UpdateAccountResponse struct {
	Message string `json:"message"`
	User    User   `json:"user"`
}

// PasswordReset represents a password reset code generated by an admin.
type PasswordReset struct {
	ID        int64      `json:"id"`
	UserID    int64      `json:"user_id"`
	Code      string     `json:"code"`
	CreatedBy int64      `json:"created_by"`
	UsedAt    *time.Time `json:"used_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	CreatedAt time.Time  `json:"created_at"`
}

// CreateResetResponse is the response from POST /api/users/{id}/reset.
type CreateResetResponse struct {
	Code      string `json:"code"`
	ExpiresAt string `json:"expires_at"`
}

// ResetPasswordRequest is the payload for POST /api/auth/reset-password.
type ResetPasswordRequest struct {
	Code        string `json:"code"`
	NewPassword string `json:"new_password"`
}

// UpdateUserRoleRequest is the payload for PUT /api/users/{id}/role.
type UpdateUserRoleRequest struct {
	Role string `json:"role"`
}

// CreateInviteRequest is the payload for POST /api/invites.
type CreateInviteRequest struct {
	Role string `json:"role"`
}

// CreateInviteResponse is the response from POST /api/invites.
type CreateInviteResponse struct {
	Code      string `json:"code"`
	Role      string `json:"role"`
	ExpiresAt string `json:"expires_at"`
}
